// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentasWeb;

#nullable disable

namespace VentasWeb.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("VentasWeb.Models.ArticuloExcluido", b =>
                {
                    b.Property<string>("SKU")
                        .HasColumnType("TEXT");

                    b.HasKey("SKU");

                    b.ToTable("Web_ArticulosExcluidos", "dbo");
                });

            modelBuilder.Entity("VentasWeb.Models.FamiliaExcluida", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Web_FamiliasExcluidas", "dbo");
                });

            modelBuilder.Entity("VentasWeb.Models.PrecioForzado", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FranjaMkp")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PrecioLista")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecioVenta")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Sku");

                    b.ToTable("Web_PreciosForzados", "dbo");
                });

            modelBuilder.Entity("VentasWeb.Models.SucursalExcluida", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Numero");

                    b.ToTable("Web_SucursalesExcluidas", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
